---
# Defines deployment design and assigns role to server groups

- hosts: localhost
  gather_facts: false
  become: True
  vars:
      fsid: "e8ba1fe2-dbf6-4b15-b0ca-2c5ffd97f59e"
      public_network: 172.16.41.0/24
      cluster_network: 172.16.41.0/24
      journal_size: 100
      journal_collocation: true
      devices: []
      cluster: ceph
      osd_objectstore: filestore
      osd_group_name: osds
      #lookup_disks: "{'storage_disks': {'model': 'SAMSUNG MZ7LN512', 'rotational': '0',  'ceph_type' : 'data', 'count': 2 }}"
      lookup_disks: "{'storage_disks': {'vendor': '0x1af4', 'ceph_type' : 'data', 'size': 'gte(30 GB)', 'count': 2 }}"
      legacy_devices: []
#      legacy_lookup_disks: "/dev/sda /dev/sdb /dev/sdc"
  pre_tasks:
    # If we can't get python2 installed before any module is used we will fail
    # so just try what we can to get it installed
    - name: gathering facts
      setup:
    - name: choose disk
      choose_disk:
        facts: "{{ansible_devices}}"
        disks: "{{lookup_disks}}"
#       legacy_disks: "{{legacy_lookup_disks}}"
    - debug: var=storage_devices
    - debug: var=journal_devices
    - debug: var=legacy_devices
    - debug: var=legacy_raw_journal_devices
    - debug: var=devices_to_activate
  roles:
    - ceph-osd
